version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update VARIANT to pick a node version: 10, 12, 14
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
    
    environment: 
      TZ: Asia/Seoul
      LC_ALL: en_US.UTF-8

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity


    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
      TZ: Asia/Seoul
      LC_ALL: en_US.UTF-8

    # Runs MariaDB on the same network as the app container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:app


    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mariadb-data:
